### ISSUE TITLE
CSS "line-height"

### ISSUE THREAD

**Issue by pensierinmusica** [sapegin/grunt-webfont#235]
Hi,

I noticed that the CSS file generated by "grunt-webfont" contains a general class for the iconfont with a property

```css
{
  line-height: 1;
}
```

This is causing some weird alignment in my current project, so I'm overriding the property with another rule.

I wonder if there's a precise reason to not keep

```css
{
  line-height: inherit;
}
```

Or if it's just a minor bug that can be fixed.

Thanks!
