### ISSUE TITLE
The mapping values keeps changing after each build

### ISSUE THREAD

**Issue by josephj** [sapegin/grunt-webfont#246]
I occasionally need to access webfont icons from **CSS attributes** instead of HTML tags.

````css
.annoucement:before { 
    font-family: 'font-superawesone';
    content: '\f101';
}
````

Recently I realised the mapping values keep changing after each build. This doesn't happen in FontCustom. I think it's because they have a manifest file. Is there any option in grunt-webfont which I can prevent values from being changed?
