### ISSUE TITLE
Semver and hashes going wrong

### ISSUE THREAD

**Issue by kaspereden** [sapegin/grunt-webfont#248]
When I generate a font with default setting hashes to true an error occurs in the url names...

```css
@font-face {
	font-family:"my-icon-1.0.18";
	src:url("../../build/fonts/my-icon-1.0?42eade60875d16742835116fb4f894e6.18.eot");
	src:url("../../build/fonts/my-icon-1.0.18.eot?#iefix") format("embedded-opentype"),
		url("../../build/fonts/my-icon-1.0?42eade60875d16742835116fb4f894e6.18.woff") format("woff"),
		url("../../build/fonts/my-icon-1.0?42eade60875d16742835116fb4f894e6.18.ttf") format("truetype");
	font-weight:normal;
	font-style:normal;
}
```
When I turn it off then the filenames are correct.
```css
@font-face {
	font-family:"my-icon-1.0.18";
	src:url("../../build/fonts/my-icon-1.0.18.eot");
	src:url("../../build/fonts/my-icon-1.0.18.eot?#iefix") format("embedded-opentype"),
		url("../../build/fonts/my-icon-1.0.18.woff") format("woff"),
		url("../../build/fonts/my-icon-1.0.18.ttf") format("truetype");
	font-weight:normal;
	font-style:normal;
}
```

I am using the font option to append a version number to the font. 
```javascript
                    font: 'my-icon-<%= pkg.version %>',
```

For some reason the first 2 numbers (major.minor) are handled correctly but the last (patch) is not.
