### ISSUE TITLE
Use of placeholders

### ISSUE THREAD

**Issue by brunowego** [sapegin/grunt-webfont#305]
What you think about add a placeholder for each icon? It will help developers to use specific icon in another class.

**Comment by sapegin** [comment]
No sure I understand what you mean.

**Comment by brunowego** [comment]
Instead of extending a class, extend a placeholder. See the example below:

```scss
%i--view-quilt-head,
.i--view-quilt-head:before {
    content: '\f145';
}
```

```scss
&--asc:before {
    @extend %i--sort-asc;
}
```
