### ISSUE TITLE
How to put custom templates outside of node_modules?

### ISSUE THREAD

**Issue by Wolfr** [sapegin/grunt-webfont#67]
First of all I want to thank you for the work on Grunt webfont. This has really helped in my projects.

I have a fairly extensive system that generates 3 different webfonts, it uses 3 different templates.

Here is a part of the Gruntfile I use to generate the fonts:

```
# generate 3 webfonts, one for Android system, once for iOS system, one for the app itself
webfont:
    iconsapp:
        src: 'images/icons_svg_source/app/*.svg'
        dest: '.tmp/fonts'
        destCss: 'scss/clank/icon-fonts'
        options:
            font: 'app-icons'
            hashes: false
            htmlDemo: false
            stylesheet: 'scss'
            relativeFontPath: '../fonts'
            syntax: 'custom-app'
    iconsandroid:
        src: 'images/icons_svg_source/android/*.svg'
        dest: '.tmp/fonts'
        destCss: 'scss/clank/icon-fonts'
        options:
            font: 'android-icons'
            hashes: false
            htmlDemo: false
            stylesheet: 'scss'
            relativeFontPath: '../fonts'
            syntax: 'custom-android'
    iconsios:
        src: 'images/icons_svg_source/ios/*.svg'
        dest: '.tmp/fonts'
        destCss: 'scss/clank/icon-fonts'
        options:
            font: 'ios-icons'
            hashes: false
            htmlDemo: false
            stylesheet: 'scss'
            relativeFontPath: '../fonts'
            syntax: 'custom-ios'
```

As you can see 3 different fonts are generated with 3 different custom templates.

Now, I want to put the custom syntaxes somewhere else than in `node-modules/grunt-webfont/tasks/templates`.

You're not supposed project info in `node-modules` for obvious reasons: the folder is often not versioned, and needs to update separately from your project.

If I set syntax to a custom path for example "/font-generation-templates/custom-app" I can't seem to "leave" the node-modules folder using '/' or '../'

For example, setting syntax to `/font-generation-templates/custom-app' returns this error:

  Error: ENOENT, no such file or directory '/Users/noone/Sites/pyxbyb/node_modules/grunt-webfont/tasks/templates/font-generation-templates/custom-app.css'

Obviously the directory does not exist, but what I really want to do is reference a directory in the root of my folder.

Am I missing something or is it not possible to have templates live outside the `node-modules/grunt-webfont/tasks/templates` folder?
